/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserpostRouteImport } from './routes/userpost'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostanalysisRouteImport } from './routes/postanalysis'
import { Route as LikeforumRouteImport } from './routes/likeforum'
import { Route as FollowRouteImport } from './routes/follow'
import { Route as FanRouteImport } from './routes/fan'
import { Route as IndexRouteImport } from './routes/index'

const UserpostRoute = UserpostRouteImport.update({
  id: '/userpost',
  path: '/userpost',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostanalysisRoute = PostanalysisRouteImport.update({
  id: '/postanalysis',
  path: '/postanalysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LikeforumRoute = LikeforumRouteImport.update({
  id: '/likeforum',
  path: '/likeforum',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowRoute = FollowRouteImport.update({
  id: '/follow',
  path: '/follow',
  getParentRoute: () => rootRouteImport,
} as any)
const FanRoute = FanRouteImport.update({
  id: '/fan',
  path: '/fan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fan': typeof FanRoute
  '/follow': typeof FollowRoute
  '/likeforum': typeof LikeforumRoute
  '/postanalysis': typeof PostanalysisRoute
  '/profile': typeof ProfileRoute
  '/userpost': typeof UserpostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fan': typeof FanRoute
  '/follow': typeof FollowRoute
  '/likeforum': typeof LikeforumRoute
  '/postanalysis': typeof PostanalysisRoute
  '/profile': typeof ProfileRoute
  '/userpost': typeof UserpostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fan': typeof FanRoute
  '/follow': typeof FollowRoute
  '/likeforum': typeof LikeforumRoute
  '/postanalysis': typeof PostanalysisRoute
  '/profile': typeof ProfileRoute
  '/userpost': typeof UserpostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fan'
    | '/follow'
    | '/likeforum'
    | '/postanalysis'
    | '/profile'
    | '/userpost'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fan'
    | '/follow'
    | '/likeforum'
    | '/postanalysis'
    | '/profile'
    | '/userpost'
  id:
    | '__root__'
    | '/'
    | '/fan'
    | '/follow'
    | '/likeforum'
    | '/postanalysis'
    | '/profile'
    | '/userpost'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FanRoute: typeof FanRoute
  FollowRoute: typeof FollowRoute
  LikeforumRoute: typeof LikeforumRoute
  PostanalysisRoute: typeof PostanalysisRoute
  ProfileRoute: typeof ProfileRoute
  UserpostRoute: typeof UserpostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userpost': {
      id: '/userpost'
      path: '/userpost'
      fullPath: '/userpost'
      preLoaderRoute: typeof UserpostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postanalysis': {
      id: '/postanalysis'
      path: '/postanalysis'
      fullPath: '/postanalysis'
      preLoaderRoute: typeof PostanalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likeforum': {
      id: '/likeforum'
      path: '/likeforum'
      fullPath: '/likeforum'
      preLoaderRoute: typeof LikeforumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow': {
      id: '/follow'
      path: '/follow'
      fullPath: '/follow'
      preLoaderRoute: typeof FollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan': {
      id: '/fan'
      path: '/fan'
      fullPath: '/fan'
      preLoaderRoute: typeof FanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FanRoute: FanRoute,
  FollowRoute: FollowRoute,
  LikeforumRoute: LikeforumRoute,
  PostanalysisRoute: PostanalysisRoute,
  ProfileRoute: ProfileRoute,
  UserpostRoute: UserpostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
