/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserpostRouteImport } from './routes/userpost'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostsearchRouteImport } from './routes/postsearch'
import { Route as PostanalysisRouteImport } from './routes/postanalysis'
import { Route as LikeforumRouteImport } from './routes/likeforum'
import { Route as ForumpostRouteImport } from './routes/forumpost'
import { Route as FollowRouteImport } from './routes/follow'
import { Route as FanRouteImport } from './routes/fan'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DbanalyzeRouteImport } from './routes/dbanalyze'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DbanalyzeIndexRouteImport } from './routes/dbanalyze/index'
import { Route as DbanalyzeManageRouteImport } from './routes/dbanalyze/manage'
import { Route as DbanalyzeExploreRouteImport } from './routes/dbanalyze/explore'

const UserpostRoute = UserpostRouteImport.update({
  id: '/userpost',
  path: '/userpost',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsearchRoute = PostsearchRouteImport.update({
  id: '/postsearch',
  path: '/postsearch',
  getParentRoute: () => rootRouteImport,
} as any)
const PostanalysisRoute = PostanalysisRouteImport.update({
  id: '/postanalysis',
  path: '/postanalysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LikeforumRoute = LikeforumRouteImport.update({
  id: '/likeforum',
  path: '/likeforum',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumpostRoute = ForumpostRouteImport.update({
  id: '/forumpost',
  path: '/forumpost',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowRoute = FollowRouteImport.update({
  id: '/follow',
  path: '/follow',
  getParentRoute: () => rootRouteImport,
} as any)
const FanRoute = FanRouteImport.update({
  id: '/fan',
  path: '/fan',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DbanalyzeRoute = DbanalyzeRouteImport.update({
  id: '/dbanalyze',
  path: '/dbanalyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DbanalyzeIndexRoute = DbanalyzeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DbanalyzeRoute,
} as any)
const DbanalyzeManageRoute = DbanalyzeManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => DbanalyzeRoute,
} as any)
const DbanalyzeExploreRoute = DbanalyzeExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => DbanalyzeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dbanalyze': typeof DbanalyzeRouteWithChildren
  '/export': typeof ExportRoute
  '/fan': typeof FanRoute
  '/follow': typeof FollowRoute
  '/forumpost': typeof ForumpostRoute
  '/likeforum': typeof LikeforumRoute
  '/postanalysis': typeof PostanalysisRoute
  '/postsearch': typeof PostsearchRoute
  '/profile': typeof ProfileRoute
  '/userpost': typeof UserpostRoute
  '/dbanalyze/explore': typeof DbanalyzeExploreRoute
  '/dbanalyze/manage': typeof DbanalyzeManageRoute
  '/dbanalyze/': typeof DbanalyzeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/export': typeof ExportRoute
  '/fan': typeof FanRoute
  '/follow': typeof FollowRoute
  '/forumpost': typeof ForumpostRoute
  '/likeforum': typeof LikeforumRoute
  '/postanalysis': typeof PostanalysisRoute
  '/postsearch': typeof PostsearchRoute
  '/profile': typeof ProfileRoute
  '/userpost': typeof UserpostRoute
  '/dbanalyze/explore': typeof DbanalyzeExploreRoute
  '/dbanalyze/manage': typeof DbanalyzeManageRoute
  '/dbanalyze': typeof DbanalyzeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dbanalyze': typeof DbanalyzeRouteWithChildren
  '/export': typeof ExportRoute
  '/fan': typeof FanRoute
  '/follow': typeof FollowRoute
  '/forumpost': typeof ForumpostRoute
  '/likeforum': typeof LikeforumRoute
  '/postanalysis': typeof PostanalysisRoute
  '/postsearch': typeof PostsearchRoute
  '/profile': typeof ProfileRoute
  '/userpost': typeof UserpostRoute
  '/dbanalyze/explore': typeof DbanalyzeExploreRoute
  '/dbanalyze/manage': typeof DbanalyzeManageRoute
  '/dbanalyze/': typeof DbanalyzeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dbanalyze'
    | '/export'
    | '/fan'
    | '/follow'
    | '/forumpost'
    | '/likeforum'
    | '/postanalysis'
    | '/postsearch'
    | '/profile'
    | '/userpost'
    | '/dbanalyze/explore'
    | '/dbanalyze/manage'
    | '/dbanalyze/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/export'
    | '/fan'
    | '/follow'
    | '/forumpost'
    | '/likeforum'
    | '/postanalysis'
    | '/postsearch'
    | '/profile'
    | '/userpost'
    | '/dbanalyze/explore'
    | '/dbanalyze/manage'
    | '/dbanalyze'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dbanalyze'
    | '/export'
    | '/fan'
    | '/follow'
    | '/forumpost'
    | '/likeforum'
    | '/postanalysis'
    | '/postsearch'
    | '/profile'
    | '/userpost'
    | '/dbanalyze/explore'
    | '/dbanalyze/manage'
    | '/dbanalyze/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DbanalyzeRoute: typeof DbanalyzeRouteWithChildren
  ExportRoute: typeof ExportRoute
  FanRoute: typeof FanRoute
  FollowRoute: typeof FollowRoute
  ForumpostRoute: typeof ForumpostRoute
  LikeforumRoute: typeof LikeforumRoute
  PostanalysisRoute: typeof PostanalysisRoute
  PostsearchRoute: typeof PostsearchRoute
  ProfileRoute: typeof ProfileRoute
  UserpostRoute: typeof UserpostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userpost': {
      id: '/userpost'
      path: '/userpost'
      fullPath: '/userpost'
      preLoaderRoute: typeof UserpostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postsearch': {
      id: '/postsearch'
      path: '/postsearch'
      fullPath: '/postsearch'
      preLoaderRoute: typeof PostsearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postanalysis': {
      id: '/postanalysis'
      path: '/postanalysis'
      fullPath: '/postanalysis'
      preLoaderRoute: typeof PostanalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likeforum': {
      id: '/likeforum'
      path: '/likeforum'
      fullPath: '/likeforum'
      preLoaderRoute: typeof LikeforumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forumpost': {
      id: '/forumpost'
      path: '/forumpost'
      fullPath: '/forumpost'
      preLoaderRoute: typeof ForumpostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow': {
      id: '/follow'
      path: '/follow'
      fullPath: '/follow'
      preLoaderRoute: typeof FollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan': {
      id: '/fan'
      path: '/fan'
      fullPath: '/fan'
      preLoaderRoute: typeof FanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dbanalyze': {
      id: '/dbanalyze'
      path: '/dbanalyze'
      fullPath: '/dbanalyze'
      preLoaderRoute: typeof DbanalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dbanalyze/': {
      id: '/dbanalyze/'
      path: '/'
      fullPath: '/dbanalyze/'
      preLoaderRoute: typeof DbanalyzeIndexRouteImport
      parentRoute: typeof DbanalyzeRoute
    }
    '/dbanalyze/manage': {
      id: '/dbanalyze/manage'
      path: '/manage'
      fullPath: '/dbanalyze/manage'
      preLoaderRoute: typeof DbanalyzeManageRouteImport
      parentRoute: typeof DbanalyzeRoute
    }
    '/dbanalyze/explore': {
      id: '/dbanalyze/explore'
      path: '/explore'
      fullPath: '/dbanalyze/explore'
      preLoaderRoute: typeof DbanalyzeExploreRouteImport
      parentRoute: typeof DbanalyzeRoute
    }
  }
}

interface DbanalyzeRouteChildren {
  DbanalyzeExploreRoute: typeof DbanalyzeExploreRoute
  DbanalyzeManageRoute: typeof DbanalyzeManageRoute
  DbanalyzeIndexRoute: typeof DbanalyzeIndexRoute
}

const DbanalyzeRouteChildren: DbanalyzeRouteChildren = {
  DbanalyzeExploreRoute: DbanalyzeExploreRoute,
  DbanalyzeManageRoute: DbanalyzeManageRoute,
  DbanalyzeIndexRoute: DbanalyzeIndexRoute,
}

const DbanalyzeRouteWithChildren = DbanalyzeRoute._addFileChildren(
  DbanalyzeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DbanalyzeRoute: DbanalyzeRouteWithChildren,
  ExportRoute: ExportRoute,
  FanRoute: FanRoute,
  FollowRoute: FollowRoute,
  ForumpostRoute: ForumpostRoute,
  LikeforumRoute: LikeforumRoute,
  PostanalysisRoute: PostanalysisRoute,
  PostsearchRoute: PostsearchRoute,
  ProfileRoute: ProfileRoute,
  UserpostRoute: UserpostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
